// <auto-generated />
namespace WebAppSchool.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_student_newproperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_student_newproperty));
        
        string IMigrationMetadata.Id
        {
            get { return "201611211655042_add_student_newproperty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
